# Generated by Django 5.1.5 on 2025-02-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('npk_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('standard_quantity_per_hectare', models.FloatField(default=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(default='https://example.com/default_fertilizer.jpg')),
                ('buy_link', models.URLField(default='https://example.com/fertilizers')),
            ],
        ),
    ]
