# Generated by Django 5.1.5 on 2025-02-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_fertilizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerName', models.CharField(max_length=255)),
                ('crop_name', models.CharField(max_length=255)),
                ('crop_translation', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cropyieldprediction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fertilizerrecommendation',
            name='user',
        ),
        migrations.DeleteModel(
            name='CropRecommendation',
        ),
        migrations.DeleteModel(
            name='CropYieldPrediction',
        ),
        migrations.DeleteModel(
            name='FertilizerRecommendation',
        ),
    ]
