# Generated by Django 5.1.5 on 2025-02-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_savedcrop_remove_cropyieldprediction_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcrop',
            name='user_entered_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
