# Generated by Django 5.1.5 on 2025-03-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_savedcrop_user_entered_values'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedCrop',
        ),
    ]
