# Generated by Django 5.1.5 on 2025-03-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_delete_savedcrop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmerName', models.CharField(max_length=255)),
                ('crop_name', models.CharField(max_length=255)),
                ('crop_translation', models.CharField(max_length=255)),
                ('user_entered_values', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
